version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6378:6379"

  selenium-chrome:
    image: selenium/standalone-chrome:latest
    restart: always
    ports:
      - "4444:4444"

volumes:
  postgres_data: