"""initial

Revision ID: 6c46925c9d8d
Revises: 
Create Date: 2024-02-26 19:07:03.266181

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c46925c9d8d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course",
        sa.Column("course_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("course_number", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("course_id"),
    )
    op.create_table(
        "weekday",
        sa.Column("weekday_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("weekday_name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("weekday_id"),
    )
    op.create_table(
        "group",
        sa.Column("group_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group_number", sa.SmallInteger(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"], ["course.course_id"], onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("group_id"),
    )
    op.create_table(
        "lesson",
        sa.Column("lesson_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("weekday_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.TIME(), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["group.group_id"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(
            ["weekday_id"], ["weekday.weekday_id"], onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("lesson_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lesson")
    op.drop_table("group")
    op.drop_table("weekday")
    op.drop_table("course")
    # ### end Alembic commands ###
