"""subs

Revision ID: 73b06cf6c977
Revises: 6c46925c9d8d
Create Date: 2024-03-01 19:58:05.021879

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73b06cf6c977"
down_revision: Union[str, None] = "6c46925c9d8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lecture",
        sa.Column("lecture_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group_name", sa.String(length=255), nullable=False),
        sa.Column("lecture_number", sa.SmallInteger(), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("substitute_teacher", sa.String(length=255), nullable=False),
        sa.Column("new_subject", sa.String(length=255), nullable=False),
        sa.Column("classroom", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("lecture_id"),
    )
    op.create_table(
        "schedule",
        sa.Column("schedule_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("day", sa.String(length=255), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("schedule_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("schedule")
    op.drop_table("lecture")
    # ### end Alembic commands ###
